### ISSUE TITLE
Split Client Active Directory model from data-transfer model when publishing CloudEvents

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.backgroundjobs#100]
**Is your feature request related to a problem? Please describe.**
When receiving secrets from the Azure Active Directory, the same model is used to both retrieve the correct secrets as well to send CloudEvents to Azure Event Grid. This can possible lead to security issues when we want to enhance the `AzureApplication` model because it would immediately mean we enhance the transfer object for the event, making it public. 

**Describe the solution you'd like**
Split the models into 2 so we have more control over what needs to be internal and what can be published.

**Comment by stijnmoreels** [comment]
Something you can agree on, @pim-simons ?

**Comment by pim-simons** [comment]
Just to check, you want a seperate model to use here: https://github.com/arcus-azure/arcus.backgroundjobs/blob/e392e5d3af43dbd5038cbe22e41fb8b94528fc86/src/Arcus.BackgroundJobs.AzureActiveDirectory/ClientSecretExpirationJobOptions.cs#L86

I don't really see a problem with that, if it removes a possible issue later on than I'm all for it 👍🏻

**Comment by stijnmoreels** [comment]
> Just to check, you want a seperate model to use here:

Yep, that's the one. Some separated event as in `AzureApplicationEvent` or so. 
Now we use the `KeyId` of the secret. Is that a possible vulnerability risk?

**Comment by pim-simons** [comment]
> 
> 
> > Just to check, you want a seperate model to use here:
> 
> Yep, that's the one. Some separated event as in `AzureApplicationEvent` or so. Now we use the `KeyId` of the secret. Is that a possible vulnerability risk?

I'm not a security person 👀  but I don't see that much harm in using the `KeyId`. As far as I know it is just an identifier of the secret that has expired.

**Comment by stijnmoreels** [comment]
This can also be my paranoia speaking, but it still feels like a good idea. Splitting the domain and the transfer models.

**Comment by stijnmoreels** [comment]
I'll add @fgheysels to ask his view too 😄 .

**Comment by stijnmoreels** [comment]
On the other hand, the internal model here is rather the `PasswordCredential` and the `AzureApplication` is already a sub-set of those values, so in that context it is already split. An extra description on the `AzureApplication` model could be useful to explain that this model is used for event tracking.
