### ISSUE TITLE
Consider making the `ClientSecretExpirationJobOptions.EventUri` required in the background job registration

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.backgroundjobs#137]
**Is your feature request related to a problem? Please describe.**
When a `ClientSecretExpirationJob` is registered in the application, one can choose to configure additional options. One of those options, though, called `EventUri`, is required for the job to run successfully, but can be omitted when registering the job.

**Describe the solution you'd like**
Either make the `EventUri` required during the registration, or provide a default URI that the job can use when publishing events.

**Comment by stijnmoreels** [comment]
Is it an option that we don't let the background job publish the event? That we only log it as an event and that the consumer decides how the application should react to it? Bit like we did in the Databricks background job?

**Comment by stijnmoreels** [comment]
Maybe @pim-simons can shed some light here as well?

Also something that is a bit related to this: saw that the name of the telemetry event that is now written to Application Insights on each job run is now used to provide a description of the event where the Azure Application ID is repeated (is already in the telemetry context). Can this be simplified to `"Azure Application secret expired"` or something in the like? And move the description now to an entry in the telemetry context?

**Comment by pim-simons** [comment]
> Maybe @pim-simons can shed some light here as well?
> 
> Also something that is a bit related to this: saw that the name of the telemetry event that is now written to Application Insights on each job run is now used to provide a description of the event where the Azure Application ID is repeated (is already in the telemetry context). Can this be simplified to `"Azure Application secret expired"` or something in the like? And move the description to an entry in the telemetry context?

I think we can indeed change the logging to  `"Azure Application secret expired"`, seems a bit cleaner.

>Is it an option that we don't let the background job publish the event? That we only log it as an event and that the consumer decides how the application should react to it? Bit like we did in the Databricks background job?

Do you mean just loggint it as an event within Application Insights? 
Personally I would keep the EventGrid implementation, as I use that to further process the event (for example I use a Logic App to subscribe on the event and then sent out an email to admins).

**Comment by stijnmoreels** [comment]
> Do you mean just loggint it as an event within Application Insights?
Personally I would keep the EventGrid implementation, as I use that to further process the event (for example I use a Logic App to subscribe on the event and then sent out an email to admins).

Yeah, I meant just logging it and that the consumer by themselves set up the EventGrid infrastructure (if there's a need for one), but yeah, maybe it will always be needed and then it's a good thing that we provide it instead. Ok, let's leave that part as-is. Only we should make sure that the 'EventUri' is then mandatory or at least provided with a default so that the job doesn't fail with no options provided.
