### ISSUE TITLE
Add `<remarks/>` to background job registrations that need additional services

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.backgroundjobs#140]
**Is your feature request related to a problem? Please describe.**
When registering a background job, the job usually requires additional registered services for it to work. An example is the CloudEvents background job that needs an Arcus secret store registration to retrieve the Azure Service Bus topic connection string for the message pump.
These requirements are written on the feature documentation site, but are missing in the code documentation.

**Describe the solution you'd like**
Adds the necessary `<remarks/>` tags on all the background jobs that need additional registered services. Where possible, even initialize the background job yourself and throw an `InvalidOperationException` with a similar description as the code remarks when such a service is not available. One can point to the dedicated documentation sites where those additional services are explained. 

**Additional context**
First mentioned in #139

**Comment by fgheysels** [comment]
I think failing fast with a clear exception message is always a good thing.   It can save you a tremendous lot of time.
