### ISSUE TITLE
Provide background job to query Databricks and report job outcome as metric

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.backgroundjobs#26]
As of today, Azure Databricks does not integrate with Azure Monitor so it's hard to alert on failed jobs.

We should provide a background job that queries the Databricks cluster for the jobs that completed in a given window and report the outcome as a custom metric in Application Insights.

**Comment by tomkerkhove** [comment]
Databricks client - https://github.com/Azure/azure-databricks-client

**Comment by stijnmoreels** [comment]
Can you give some infrastructure and guidance for this? I'll be happy to pick this up.

**Comment by tomkerkhove** [comment]
Sent offline

**Comment by tomkerkhove** [comment]
@stijnmoreels Can we provide some docs on how to use the databricks info provider?

**Comment by stijnmoreels** [comment]
> @stijnmoreels Can we provide some docs on how to use the databricks info provider?

I thought we already had these: https://github.com/arcus-azure/arcus.backgroundjobs/blob/master/docs/preview/features/databricks/job-metrics.md?

**Comment by tomkerkhove** [comment]
That's just for the background jobs but not how to use it with the providers themselves; for example if you want to use it in a function
