### ISSUE TITLE
Subscription names are not truncated when starting a job

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.backgroundjobs#67]
**Describe the bug**
Subscription names are not truncated when starting a job which can cause issues with regards to length

> System.ArgumentOutOfRangeException: Entity path 'Example-KeyVault-Cache-Invalidate.1feea6d5-0c93-4c1d-ba9c-edf74acb523e' exceeds the '50' character limit. (Parameter 'subscriptionName')

**To Reproduce**
1. Use `Example-KeyVault-Cache-Invalidate` as a prefix for the subscription
2. Exception thrown

**Expected behavior**
Subscription gets created with truncated name.

**Alternative**
Ensure that the specified `subscriptionNamePrefix` is only 13 chars long

**Comment by stijnmoreels** [comment]
Hmm, if we truncate it, maybe that can lead to problems as it implicitly does it for us. We may log a warning if we truncate.

Ensuring that the prefix is shorter will probably not helping always if we allow the full subscription name to be altered.
