### ISSUE TITLE
Provide support for specifying the topic name

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.backgroundjobs#68]
**Is your feature request related to a problem? Please describe.**
Users are forced to use entity-scoped namespaces, which is not always ideal.

**Describe the solution you'd like**
Provide support for specifying the topic name so that users can use namespace-scoped connection strings.

**Describe alternatives you've considered**
N/A

**Comment by stijnmoreels** [comment]
Ah, yes, that will be more in line with the other messaging stuff we have.
