### ISSUE TITLE
Provide background job for asynchronous configuration changes in Azure App Configuration

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.backgroundjobs#80]
**Is your feature request related to a problem? Please describe.**
Provide background job for asynchronous configuration changes in Azure App Configuration so that instances can refresh the values

**Describe the solution you'd like**
An approach similar to Azure Key Vault invalidation.

**Describe alternatives you've considered**
N/A

**Additional context**
@gverstraete can help here.

Reload data from Azure App Configuration: https://docs.microsoft.com/en-us/azure/azure-app-configuration/enable-dynamic-configuration-dotnet-core#reload-data-from-app-configuration

**Comment by gverstraete** [comment]
Please also include the possiblity to add Azure App Configuration Feature Flag toggle changes...

I did this before and can share some code if you want @stijnmoreels  ;)

**Comment by stijnmoreels** [comment]
> Please also include the possiblity to add Azure App Configuration Feature Flag toggle changes...
> 
> I did this before and can share some code if you want @stijnmoreels ;)

Aha, good points, should be the same event though, I guess, since the feature toggles are also saved as key-value pairs in the config?

**Comment by gverstraete** [comment]
> > Please also include the possiblity to add Azure App Configuration Feature Flag toggle changes...
> > I did this before and can share some code if you want @stijnmoreels ;)
> 
> Aha, good point, should be the same event though, I guess, since the feature toggles are also saved as key-value pairs in the config?

Good point :) just checked with my team. It seems it is :)

**Comment by stijnmoreels** [comment]
> > > Please also include the possiblity to add Azure App Configuration Feature Flag toggle changes...
> > > I did this before and can share some code if you want @stijnmoreels ;)
> > 
> > 
> > Aha, good point, should be the same event though, I guess, since the feature toggles are also saved as key-value pairs in the config?
> 
> Good point :) just checked with my team. It seems it is :)

We'll add an integration test to both check for changes in normal key-value pairs as well as feature flags. Thx for remining us! 👍
