### ISSUE TITLE
Provide background job to discover Azure AD apps that are about to expire

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.backgroundjobs#81]
**Is your feature request related to a problem? Please describe.**
Provide background job to discover Azure AD apps that are about to expire and emit Azure Event Grid events for them.

**Comment by tomkerkhove** [comment]
@pim-simons is willing to contribute this.

What event type & payload do you have in mind?

**Comment by pim-simons** [comment]
> What event type & payload do you have in mind?

In my project I am using the types `ClientSecretAboutToExpire` and `ClientSecretExpired` and as payload I am using:
```
{
    "displayName": "application name",
    "endDateTime": "2020-03-16T10:45:06",
    "keyId": "8a196371-1ad7-4f2b-8609-05bc5b6f7c27"
}
```

But very much open to suggestions or improvements on this.

**Comment by pim-simons** [comment]
We probably also need to take a look at making the window for the `ClientSecretAboutToExpire` event settable, right now I have it set hardcoded to 14 days which might not be the right value for every user.

**Comment by tomkerkhove** [comment]
What information do we have access to?

Things I'm thinking:
- Application Id
- Tenant Id (in case you have multiple)
- Object Id
- Owner



> We probably also need to take a look at making the window for the `ClientSecretAboutToExpire` event settable, right now I have it set hardcoded to 14 days which might not be the right value for every user.

Sounds like a plan, because potentially you'd want to have notifications at 1 month, 14 days, 7 days and 1 day.

**Comment by fgheysels** [comment]
I've already opened an issue in the original project, but wouldn't it be possible to use Azure Managed Identity to query Azure AD instead of using a separate app registration & client secret ?
https://github.com/pim-simons/azuread.application.clientsecret.expiration/issues/1

**Comment by tomkerkhove** [comment]
Both options are viable imo

**Comment by tomkerkhove** [comment]
Both for querying Azure AD and pushing to Azure Event Grid:
https://docs.microsoft.com/en-us/azure/event-grid/authenticate-with-active-directory

**Comment by pim-simons** [comment]
Regarding publishing to Azure Event Grid using Managed Identity, I am using Arcus.EventGrid to publish the messages and as far as I can see in the documentation using Managed Identity isn't an option there. I can only find support for the authenticationkey with `.UsingAuthenticationKey(endpointKey)`.

Will take a look at using Managed Identity for calling the Graph API.

**Comment by stijnmoreels** [comment]
> Regarding publishing to Azure Event Grid using Managed Identity, I am using Arcus.EventGrid to publish the events and as far as I can see in the documentation (https://eventgrid.arcus-azure.net/features/publishing-events) using Managed Identity isn't an option there. I can only find support for the authenticationkey with `.UsingAuthenticationKey(endpointKey)`.
> 
> Will take a look at using Managed Identity for calling the Graph API.

Is this something we should support in the event grid repo, @tomkerkhove ? If so, I'll create an issue for that.

**Comment by tomkerkhove** [comment]
Yes please!

**Comment by pim-simons** [comment]
Regarding using Managed Identity for calling the Graph API, changed the code and did some tests, see https://github.com/pim-simons/azuread.application.clientsecret.expiration/issues/1

Regarding the initial setup, I don't think there is a already an Arcus background job based on an Azure Function. Is there a basic setup for Azure Functions I should adhere to? 
And for the naming, is Arcus.BackgroundJobs.AzureAD.ClientSecretExpiration a good name, or do you guys have something different in mind?

**Comment by tomkerkhove** [comment]
It's best to carve out the Azure Functions part and make sure it can be called from an Azure Function or a .NET Background Job.

Here's an example: https://github.com/arcus-azure/arcus.backgroundjobs/blob/master/src/Arcus.BackgroundJobs.Databricks/DatabricksJobMetricsJob.cs#L16

**Comment by stijnmoreels** [comment]
I think we can close this! 🎉 
Other (related) stuff can be in separate issues.
