### ISSUE TITLE
Provide support for Managed Identity authentication

### ISSUE THREAD

**Issue by meersschautarnaud** [arcus-azure/arcus.backgroundjobs#93]
**Is your feature request related to a problem? Please describe.**
Since the ServiceBus message pump can be registered using Managed Identity authentication I would like to have support for this when registering a CloudEventBackgroundJob.

**Describe the solution you'd like**
A new extension method that enables to make use of Managed Identity authentication.

**Comment by stijnmoreels** [comment]
Aha aha, yes, that's a good one we forget. Thank you for the issue! Would you like to contribute this?

**Comment by meersschautarnaud** [comment]
Yes, I would like that! 😄

**Comment by stijnmoreels** [comment]
Ok, great! We have a [contribution guide](https://github.com/arcus-azure/.github/blob/master/CONTRIBUTING.md) if you feel lost, otherwise ping me in case of any problem. Thank you! ❤️
